name: "sample react-cd pipeline"

on: 
    workflow_run:
        workflows: ["sample React-CI pipeline"]
        types: 
            - completed

jobs:
    deploy:   #name of job
        runs-on: ubuntu-latest
        
        steps:
            - name: "install nodejs"
              uses: actions/setup-node@v4
              with: 
                node-version: '21'

            - name: "setup vercel cli"
              run: npm i -g vercel

            - name: "download artifact"
              uses: actions/download-artifact@v4
              with:
                name: build
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{github.token}}

            - name: "deploy to vercel"
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdProject






