name: "sample React-CI pipeline"

on:
    push:
        branches:
            - master
            - main


jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            run: echo "prince"
            
